id: P007941
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1660
  title: སྤྱོད་འཇུག་འགྲེལ་པ་གཞུང་དོན་རབ་གསལ་སྣང་བ།
  author: ''
  volumes:
    1cf6b758293b40acb4260abdf66b45dd:
      image_group_id: I5969
      title: ''
      volume_number: 1
      total_pages: 458
      base_file: v001.txt
