id: P007941
initial_creation_type: ocr
source_metadata:
  id: bdr:W1660
  title: སྤྱོད་འཇུག་འགྲེལ་པ་གཞུང་དོན་རབ་གསལ་སྣང་བ།
  author: ''
  volumes:
    1cf6b758293b40acb4260abdf66b45dd:
      image_group_id: I5969
      title: ''
      volume_number: 1
      total_pages: 458
ebook_metadata:
  title: སྤྱོད་འཇུག་འགྲེལ་པ་གཞུང་དོན་རབ་གསལ་སྣང་བ།
  author: ''
  sku: P007941
  cover: cover.jpg
  layers:
  - pagination
